language: go
sudo: false
addons:
  apt:
    packages:
    - libev-dev

go:
- 1.7
- 1.8
install:
- go get -d -t -v ./...

test:
  script:
  - make test
  - make cover-normal
  after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go get github.com/laher/goxc
  - "./.xc-all.bash $TRAVIS_TAG"
  - find .

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JBuaQNghrwATvyFiItYUeXMGIFr7Fy7SQwnM/kk1poMBoKTo2KduC7q+E5i+H7ZJCSOmO+IFLMEhnFDaAJ4tq4JWHC6lt56KXkkVz0XNyGSc69QoSWfv8vDBClYKpyhdNVTk3O73gK+h3R7etvFiMLccYJ4zGhJ6QxQVbFv5qoA=
  file_glob: true
  file: 
  - build/*/prepare/*
  on:
    tags: true
    repo: stampzilla/stampzilla-go
    condition: $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
